OdinScoundrelOverhaul = {
    ComboSkills = {},
    DamageTypes = {
        None = "None",
        Physical = "Physical",
        Piercing = "Piercing",
        Corrosive = "Corrosive",
        Magic = "Magic",
        Chaos = "Chaos",
        Air = "Air",
        Earth = "Earth",
        Fire = "Fire",
        Poison = "Poison",
        Shadow = "Shadow",
        Water = "Water"
    },
    ElementalDamageTypes = {
        "Air",
        "Earth",
        "Fire",
        "Poison",
        "Water"
    },
    ElementalDamageBonus = {
        Air = "SHOCKED",
        Earth = "SLOWED",
        Fire = "BURNING",
        Poison = "POISONED",
        Water = "CHILLED"
    },
    UISkillProperties = {
        MultiStrike_OdinSCO_ShadowStep = "Generates 1 Combo point.",
        MultiStrike_Vault = "Generates 1 Combo point.",
        Projectile_FanOfKnives = "Generates 1 Combo point.",
        Projectile_ThrowingKnife = "Generates 1 Combo point.",
        Shout_Adrenaline = "Generates 1 Combo point.",
        Shout_OdinSCO_ShadowSlash = "Generates 1 Combo point.",
        Target_CorruptedBlade = "Generates 1 Combo point.",
        Target_Fatality = "Generates 1 Combo point.",
        Target_GagOrder = "Generates 1 Combo point.",
        Target_KneeBreaker = "Generates 1 Combo point.",
        Target_OdinSCO_FindersKeepers = "Steal 2 AP from the target.",
        Target_OdinSCO_SinisterStrike = "Generates 1 Combo point.",
        Target_SerratedEdge = "Generates 1 Combo point.",
        Target_SleepingArms = "Generates 1 Combo point.",
        Target_TerrifyingCruelty = "Generates 1 Combo point."
    },
    ScoundrelSkills = {
        Jump_CloakAndDagger= "Jump_CloakAndDagger",
        MultiStrike_OdinSCO_ShadowStep = "MultiStrike_OdinSCO_ShadowStep",
        MultiStrike_Vault= "MultiStrike_Vault",
        Projectile_Chloroform= "Projectile_Chloroform",
        Projectile_FanOfKnives = "Projectile_FanOfKnives",
        Projectile_LaunchBomber = "Projectile_LaunchBomber",
        Projectile_OdinSCO_Firecracker = "Projectile_OdinSCO_Firecracker",
        Projectile_OdinSCO_Misfire = "Projectile_OdinSCO_Misfire",
        Projectile_ThrowingKnife = "Projectile_ThrowingKnife",
        Shout_Adrenaline = "Shout_Adrenaline",
        Shout_OdinSCO_Outmaneuver = "Shout_OdinSCO_Outmaneuver",
        Shout_OdinSCO_ShadowSlash = "Shout_OdinSCO_ShadowSlash",
        Shout_OdinSCO_SlipIntoShadows = "Shout_OdinSCO_SlipIntoShadows",
        Target_CorruptedBlade = "Target_CorruptedBlade",
        Target_DaggersDrawn = "Target_DaggersDrawn",
        Target_Fatality = "Target_Fatality",
        Target_GagOrder = "Target_GagOrder",
        Target_KneeBreaker = "Target_KneeBreaker",
        Target_OdinSCO_CrawlingInfestation = "Target_OdinSCO_CrawlingInfestation",
        Target_OdinSCO_FindersKeepers = "Target_OdinSCO_FindersKeepers",
        Target_OdinSCO_Misdirection = "Target_OdinSCO_Misdirection",
        Target_OdinSCO_SinisterStrike = "Target_OdinSCO_SinisterStrike",
        Target_SerratedEdge = "Target_SerratedEdge",
        Target_SleepingArms = "Target_SleepingArms",
        Target_TerrifyingCruelty = "Target_TerrifyingCruelty"
    },
    ResistanceParams = {
        AirResistance = "Air",
        EarthResistance = "Earth",
        FireResistance = "Fire",
        PoisonResistance = "Poison",
        WaterResistance = "Water"
    }
}